name: Pipeline for prod(Frontend)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Build Docker image
        run: docker build -t dajubhai-frontend-prod-v1 .

      - name: Tag the image
        run: docker tag dajubhai-frontend-prod-v1 registry.dajuvai.com/frontend/dajubhai-frontend-prod-v1:latest

      - name: Log in to Docker registry
        run: echo "${{ secrets.REGISTRY_PASSWORD }}" |  docker login registry.dajuvai.com -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

      - name: Push Docker image to our server
        run: docker push registry.dajuvai.com/frontend/dajubhai-frontend-prod-v1:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/dajubhai-compose
            docker compose up -d dajubhai-frontend-prod

